version: '3.8'

services:
  app:
    image: app
    container_name: app
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - ${NODE_PORT}:${NODE_PORT}
      - ${VUE_PORT}:${VUE_PORT}
    environment:
      - ${NODE_ENV}:${NODE_ENV}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
