version: '3.8'

services:
  app:
    build: .
    ports:
      - ${NODE_PORT}:${NODE_PORT}
      - ${VUE_PORT}:${VUE_PORT}
    environment:
      - ${NODE_ENV}:${NODE_ENV}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
